name: Streamlit CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  streamlit-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit scikit-learn pandas numpy matplotlib seaborn plotly flake8

    - name: Lint with flake8
      run: |
        flake8 demopy.py || echo "Lint warnings — not blocking"

    - name: Verify Streamlit script exists
      run: |
        test -f demo.py || (echo "demopy.py not found!" && exit 1)

    - name: Launch Streamlit (headless check)
      run: |
        streamlit run demo.py --server.headless true &
        sleep 10
        pkill streamlit
        echo "Streamlit launched successfully"
